name = "gezichtseinder"
author = "kankerdev"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4a92a0b026ed8573be62ef5bc185874e74aa50dabf4b2080a8bfbfa06fab9b0"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
